### PR TITLE
initial client setup

### PR DESCRIPTION
**Pull request by 2alin**
I added TypeScript, Redux, React and JSS as dependencies based on our previous discussions, as well as `redux-devtools-extension`. If there's any concern, let me know.

### CODE REVIEW

**Review by crystalbohacek — APPROVED** [review]
Looks good to me.

**Comment by 2alin** [comment]
Thanks @crystalbohacek, I'll add dummy actions as @Dan-Y-Ko  suggested, then we can merge it :)

**Comment by 2alin** [comment]
Only eslint config is left.

**Review by thijsnijhof — APPROVED** [review]
Whats with the filtered list etc in the redux actions? Are they just examples you added?

**Comment by 2alin** [comment]
@thijsnijhof 
> Whats with the filtered list etc in the redux actions? Are they just examples you added?

ahmm not exactly made up examples, they are still **incomplete**, but those will be actions to set the *Community Leaderboard* filter options as well as the list received from the API in the redux store.

**Pull request merged**
